// lib/config/course_configs.dart
import 'package:lingocraft_flutter/models/course_config.dart';

final Map<String, CourseConfig> kCourseConfigs = {
  'japanese': const CourseConfig(
    id: 'japanese',
    dbAppId: 'japanese-master',
    name: 'Japanese Master',
    flag: '🇯🇵',
    primaryTextKey: 'kanji',
    transliterationKey: 'romaji',
    secondaryScriptKey: 'kana',
    labels: {
      'kanji': 'Kanji',
      'romaji': 'Rōmaji',
      'kana': 'Kana',
      'english': 'English',
    },
    hasStories: true,
    hasReading: true,
  ),
  'hungarian': const CourseConfig(
    id: 'hungarian',
    dbAppId: 'hungarian-master',
    name: 'Hungarian Master',
    flag: '🇭🇺',
    primaryTextKey: 'hungarian',
    labels: {'hungarian': 'Hungarian', 'english': 'English'},
    hasStories: true,
    hasReading: true,
  ),
  'greek': const CourseConfig(
    id: 'greek',
    dbAppId: 'greek-master',
    name: 'Modern Greek',
    flag: '🇬🇷',
    primaryTextKey: 'greek',
    transliterationKey: 'transliteration',
    labels: {
      'greek': 'Greek',
      'transliteration': 'Transliteration',
      'english': 'English',
    },
    hasStories: true,
    hasReading: true,
  ),
  'mandarin': const CourseConfig(
    id: 'mandarin',
    dbAppId: 'mandarin-master',
    name: 'Mandarin Master',
    flag: '🇹🇼',
    primaryTextKey: 'traditional',
    transliterationKey: 'pinyin',
    secondaryScriptKey: 'simplified',
    labels: {
      'traditional': 'Traditional',
      'simplified': 'Simplified',
      'pinyin': 'Pinyin',
      'english': 'English',
    },
    hasStories: true,
  ),
  'portuguese': const CourseConfig(
    id: 'portuguese',
    dbAppId: 'portuguese-master',
    name: 'Portuguese Master',
    flag: '🇵🇹',
    primaryTextKey: 'portuguese',
    labels: {'portuguese': 'Portuguese', 'english': 'English'},
    hasStories: true,
  ),
  'romanian': const CourseConfig(
    id: 'romanian',
    dbAppId: 'romanian-master',
    name: 'Romanian Master',
    flag: '🇷🇴',
    primaryTextKey: 'romanian',
    labels: {'romanian': 'Romanian', 'english': 'English'},
    hasStories: true,
  ),
  'russian': const CourseConfig(
    id: 'russian',
    dbAppId: 'russian-master',
    name: 'Russian Master',
    flag: '🇷🇺',
    primaryTextKey: 'russian',
    transliterationKey: 'transliteration',
    labels: {
      'russian': 'Russian',
      'transliteration': 'Transliteration',
      'english': 'English',
    },
    hasStories: true,
  ),
};
